name: IOS Only


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linuxBuild
          path: ' build/ios_build.tar.g'

